"""empty message

Revision ID: 13b288ed6ec9
Revises: 4896b8a69262
Create Date: 2022-01-02 11:53:22.196923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13b288ed6ec9'
down_revision = '4896b8a69262'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('complain', sa.Column('subject', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('complain', 'subject')
    # ### end Alembic commands ###
