"""empty message

Revision ID: 37d92ed6ff11
Revises: 2747065b4d34
Create Date: 2021-12-14 18:23:38.639374

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '37d92ed6ff11'
down_revision = '2747065b4d34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('otp', sa.Column('time', sa.DateTime(), nullable=True))
    op.drop_column('otp', 'unixTimeStamp')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('otp', sa.Column('unixTimeStamp', mysql.FLOAT(), nullable=True))
    op.drop_column('otp', 'time')
    # ### end Alembic commands ###
