"""empty message

Revision ID: fc1b32d61705
Revises: 5dfb855d55c0
Create Date: 2021-12-14 19:11:53.679397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc1b32d61705'
down_revision = '5dfb855d55c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('tags', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'tags')
    # ### end Alembic commands ###
